# Generated by Django 3.0.3 on 2020-04-11 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid_app', '0007_auto_20200411_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='covid_ind',
            name='date_updated',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
