# Generated by Django 3.0.3 on 2020-04-12 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid_app', '0010_feedback_enquiry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback_enquiry',
            name='date_time',
        ),
        migrations.AddField(
            model_name='feedback_enquiry',
            name='feedback',
            field=models.CharField(blank=True, db_index=True, max_length=2000, null=True),
        ),
    ]
