# Generated by Django 3.0.3 on 2020-04-12 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covid_app', '0013_auto_20200412_1252'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback_enquiry',
            old_name='feedback',
            new_name='feedback_notmandatory',
        ),
        migrations.RenameField(
            model_name='feedback_enquiry',
            old_name='name',
            new_name='name_madatory',
        ),
        migrations.RenameField(
            model_name='feedback_enquiry',
            old_name='suggestions',
            new_name='suggestions_notmandatory',
        ),
    ]
