# Generated by Django 3.0.3 on 2020-04-12 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covid_app', '0014_auto_20200412_1255'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback_enquiry',
            old_name='feedback_notmandatory',
            new_name='feedback_not_mandatory',
        ),
        migrations.RenameField(
            model_name='feedback_enquiry',
            old_name='suggestions_notmandatory',
            new_name='suggestions_not_mandatory',
        ),
    ]
