# Generated by Django 3.0.3 on 2020-04-12 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('covid_app', '0016_auto_20200412_1257'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyReply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_reply', models.ForeignKey(blank=True, max_length=2000, null=True, on_delete=django.db.models.deletion.CASCADE, to='covid_app.Feedback_Enquiry')),
            ],
        ),
    ]
