# Generated by Django 3.0.3 on 2020-04-12 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('covid_app', '0019_auto_20200412_1323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback_enquiry',
            name='my_reply',
        ),
        migrations.AddField(
            model_name='myreply',
            name='setfeedback',
            field=models.ForeignKey(blank=True, max_length=2000, null=True, on_delete=django.db.models.deletion.CASCADE, to='covid_app.Feedback_Enquiry'),
        ),
    ]
