# Generated by Django 3.0.3 on 2020-04-12 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid_app', '0020_auto_20200412_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='myreply',
            name='time',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
