# Generated by Django 3.0.3 on 2020-04-12 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid_app', '0022_feedback_enquiry_my_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback_enquiry',
            name='Enquiry_not_madatory',
            field=models.CharField(blank=True, db_index=True, max_length=2000, null=True),
        ),
    ]
