# Generated by Django 3.0.3 on 2020-04-12 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid_app', '0023_feedback_enquiry_enquiry_not_madatory'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback_enquiry',
            name='time',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
