# Generated by Django 3.0.3 on 2020-04-12 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid_app', '0024_feedback_enquiry_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback_enquiry',
            name='image',
            field=models.ImageField(blank=True, upload_to='userposts'),
        ),
    ]
