# Generated by Django 3.0.3 on 2020-04-12 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid_app', '0025_feedback_enquiry_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback_enquiry',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='userposts'),
        ),
    ]
