# Generated by Django 3.0.3 on 2020-04-12 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid_app', '0027_auto_20200412_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback_enquiry',
            name='image',
            field=models.ImageField(blank=True, upload_to='userposts'),
        ),
    ]
