# Generated by Django 3.0.3 on 2020-04-12 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covid_app', '0028_auto_20200412_1632'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback_enquiry',
            name='image',
        ),
    ]
