# Generated by Django 3.0.3 on 2020-04-13 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid_app', '0029_remove_feedback_enquiry_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='covid_data_anal',
            name='States_Conf_plot',
            field=models.ImageField(blank=True, upload_to='graphs'),
        ),
    ]
